-- Seed warehouse-specific services
-- These services are fulfilled by warehouse staff rather than field managers/crew

-- First, delete any existing warehouse services with old WSRV- IDs
DELETE FROM catalog_services WHERE service_id LIKE 'WSRV-%';

INSERT INTO catalog_services (
  service_id,
  name,
  description,
  image_url,
  tags,
  category,
  unit_of_measure,
  base_price,
  currency,
  duration_minutes,
  service_window,
  crew_required,
  attributes,
  metadata,
  managed_by,
  is_active
) VALUES
  (
    'SRV-101',
    'Inventory Audit Service',
    'Comprehensive inventory count and verification service performed by warehouse staff',
    NULL,
    ARRAY['warehouse', 'inventory', 'audit'],
    'warehouse',
    'audit',
    150.00,
    'USD',
    180,
    'business-hours',
    1,
    '{"requires_warehouse_access": true, "includes_reporting": true}'::jsonb,
    '{"managed_by": "warehouse", "service_type": "warehouse"}'::jsonb,
    'warehouse',
    TRUE
  ),
  (
    'SRV-102',
    'Product Receiving & Inspection',
    'Receiving, inspection, and shelving of incoming products',
    NULL,
    ARRAY['warehouse', 'receiving', 'inspection'],
    'warehouse',
    'shipment',
    75.00,
    'USD',
    90,
    'business-hours',
    1,
    '{"includes_quality_check": true, "requires_forklift": false}'::jsonb,
    '{"managed_by": "warehouse", "service_type": "warehouse"}'::jsonb,
    'warehouse',
    TRUE
  ),
  (
    'SRV-103',
    'Special Order Fulfillment',
    'Custom order picking, packing, and preparation for delivery',
    NULL,
    ARRAY['warehouse', 'fulfillment', 'custom'],
    'warehouse',
    'order',
    50.00,
    'USD',
    60,
    'same-day',
    1,
    '{"priority_handling": true, "custom_packaging": true}'::jsonb,
    '{"managed_by": "warehouse", "service_type": "warehouse"}'::jsonb,
    'warehouse',
    TRUE
  ),
  (
    'SRV-104',
    'Product Relabeling Service',
    'Relabeling and repackaging of products for specific requirements',
    NULL,
    ARRAY['warehouse', 'relabeling', 'packaging'],
    'warehouse',
    'unit',
    35.00,
    'USD',
    45,
    'business-hours',
    1,
    '{"includes_materials": true, "custom_labels": true}'::jsonb,
    '{"managed_by": "warehouse", "service_type": "warehouse"}'::jsonb,
    'warehouse',
    TRUE
  ),
  (
    'SRV-105',
    'Emergency Stock Retrieval',
    'After-hours emergency inventory retrieval and preparation',
    NULL,
    ARRAY['warehouse', 'emergency', 'urgent'],
    'warehouse',
    'request',
    200.00,
    'USD',
    30,
    'after-hours',
    1,
    '{"emergency_service": true, "after_hours_surcharge": true}'::jsonb,
    '{"managed_by": "warehouse", "service_type": "warehouse"}'::jsonb,
    'warehouse',
    TRUE
  ),
  (
    'SRV-106',
    'Pallet Breakdown & Distribution',
    'Breaking down bulk pallets and organizing for distribution',
    NULL,
    ARRAY['warehouse', 'distribution', 'logistics'],
    'warehouse',
    'pallet',
    85.00,
    'USD',
    120,
    'business-hours',
    1,
    '{"requires_forklift": true, "includes_sorting": true}'::jsonb,
    '{"managed_by": "warehouse", "service_type": "warehouse"}'::jsonb,
    'warehouse',
    TRUE
  ),
  (
    'SRV-107',
    'Product Return Processing',
    'Inspection, documentation, and restocking of returned products',
    NULL,
    ARRAY['warehouse', 'returns', 'inspection'],
    'warehouse',
    'return',
    45.00,
    'USD',
    60,
    'business-hours',
    1,
    '{"includes_inspection": true, "damage_documentation": true}'::jsonb,
    '{"managed_by": "warehouse", "service_type": "warehouse"}'::jsonb,
    'warehouse',
    TRUE
  ),
  (
    'SRV-108',
    'Storage Organization Service',
    'Warehouse storage optimization and organization',
    NULL,
    ARRAY['warehouse', 'organization', 'optimization'],
    'warehouse',
    'section',
    125.00,
    'USD',
    240,
    'business-hours',
    2,
    '{"includes_labeling": true, "optimization_plan": true}'::jsonb,
    '{"managed_by": "warehouse", "service_type": "warehouse"}'::jsonb,
    'warehouse',
    TRUE
  )
ON CONFLICT (service_id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  category = EXCLUDED.category,
  base_price = EXCLUDED.base_price,
  duration_minutes = EXCLUDED.duration_minutes,
  attributes = EXCLUDED.attributes,
  metadata = EXCLUDED.metadata,
  managed_by = EXCLUDED.managed_by,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();
