import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const targetFile = join(rootDir, 'src', 'version.ts');

let gitSha = 'unknown';
try {
  gitSha = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
    .toString()
    .trim();
} catch {
  // Git SHA unavailable (e.g., build from source archive)
}

const buildTime = new Date().toISOString();
const contents = `// Auto-generated by scripts/generate-version.mjs
export const APP_VERSION = '${gitSha}';
export const BUILD_TIME = '${buildTime}';
`;

mkdirSync(dirname(targetFile), { recursive: true });
writeFileSync(targetFile, contents, 'utf8');
console.log(`[version] ${gitSha} @ ${buildTime}`);
