name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install root
        run: npm install --no-audit --no-fund
      - name: Install server deps
        run: npm --prefix server install --no-audit --no-fund
      - name: Lint
        run: npm --prefix server run lint
      - name: Build
        run: npm --prefix server run build
      - name: Test
        run: npm --prefix server test -- --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT: reports/junit.xml
      - name: Upload coverage
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: server/coverage
