#!/usr/bin/env sh
if [ -f "$PWD/.husky/_/husky.sh" ]; then . "$PWD/.husky/_/husky.sh"; fi
echo "pre-push: codegen + typecheck + tests"
pnpm codegen || exit 1
pnpm run typecheck || true
pnpm test || exit 1

